export const publishCopy = {
  en: {
    basics: "1. Your product", basicsHint: "Add photos and the details a buyer needs. One size or variant per product for now.",
    ebay: "2. eBay details", ebayHint: "Choose the category by name. We will load its conditions and required item specifics.",
    review: "3. Review and publish", save: "Save and review", saving: "Saving...", draftHint: "Saves your draft. Nothing is published yet.",
    advanced: "Advanced settings", skuHint: "Created automatically if empty. Keep it unchanged after publishing to avoid duplicate listings.",
    overrides: "Different title, description or price on eBay", overridesHint: "Optional. Leave empty to use the product details above.",
    variants: "This product has variants. They will be preserved, but eBay publishing currently requires a separate single-variant product.",
    photosHint: "The first photo is the cover. Upload clear photos of the actual item.", mainPhoto: "Make cover", cover: "Cover",
    search: "Find category", searchHint: "Search in English, for example T-Shirts or Sneakers. Choose the path that matches your item.",
    category: "Category", manual: "I already have an eBay category ID", noResults: "No categories found. Try a shorter term in English.",
    change: "Change category", retry: "Try again", conditionHint: "Describe the item's actual state: new, used, with or without tags. Options depend on the category.",
    history: "Previous attempts", result: "Latest publishing result", noJobs: "Not published yet.",
    publish: "Publish to eBay", update: "Publish / update on eBay", checking: "Checking eBay requirements...", sending: "Sending...",
    checks: "Before publishing", checkHint: "Category requirements are checked before sending. eBay can still reject account or listing details.",
    productFix: "Edit product", storeFix: "Set up eBay", store: "Selling setup", storeHint: "Shipping, payment, returns and dispatch location are set once for this store.",
    connect: "Connect your eBay seller account.", setupMissing: "Choose a dispatch location and shipping, payment and return policies in your eBay store settings.",
    setupReady: "Store settings saved. They will be reused for this listing.", unsupportedMarket: "This release supports United States (USD) only.",
    pending: "Publication is in progress. Wait for the result before sending again.", checkFailed: "Could not verify eBay requirements. Nothing was sent. Try again.",
    sandbox: "Sandbox / test listing", production: "Live eBay listing", environmentUnknown: "Confirm the environment in store settings before publishing.",
    sandboxHint: "This creates a test listing, not an item for sale on the public eBay site.", productionHint: "This can create or update a real listing on eBay.",
    stock: "Stock adjustments", catalog: "Products", create: "Add product", draft: "Draft", open: "Review listing", comingSoon: "Shopify and Etsy publishing are not available yet.",
    optional: "Optional details", count: "Quantity", price: "Price (USD)", loadFailed: "Could not load publishing checks. Refresh the page before publishing."
  },
  ru: {
    basics: "1. Ваш товар", basicsHint: "Добавьте фото и информацию для покупателя. Пока один размер или вариант на товар.",
    ebay: "2. Данные для eBay", ebayHint: "Выберите категорию по названию. Мы загрузим допустимые состояния и обязательные характеристики.",
    review: "3. Проверка и публикация", save: "Сохранить и проверить", saving: "Сохраняем...", draftHint: "Сохраняется черновик. Товар ещё не публикуется.",
    advanced: "Дополнительные настройки", skuHint: "Создаётся автоматически, если оставить пустым. Не меняйте после публикации, чтобы не создать дубликат.",
    overrides: "Другое название, описание или цена на eBay", overridesHint: "Необязательно. Оставьте пустым, чтобы использовать данные товара выше.",
    variants: "У товара есть варианты. Они сохранятся, но для публикации на eBay пока нужен отдельный товар с одним вариантом.",
    photosHint: "Первое фото станет обложкой. Загрузите чёткие фото самого товара.", mainPhoto: "Сделать обложкой", cover: "Обложка",
    search: "Найти категорию", searchHint: "Ищите на английском, например T-Shirts или Sneakers. Выберите раздел, подходящий вашему товару.",
    category: "Категория", manual: "Я уже знаю ID категории eBay", noResults: "Категории не найдены. Попробуйте более короткое слово на английском.",
    change: "Изменить категорию", retry: "Повторить", conditionHint: "Укажите реальное состояние: новый, б/у, с бирками или без. Варианты зависят от категории.",
    history: "Предыдущие попытки", result: "Результат последней публикации", noJobs: "Товар ещё не опубликован.",
    publish: "Опубликовать на eBay", update: "Опубликовать / обновить на eBay", checking: "Проверяем требования eBay...", sending: "Отправляем...",
    checks: "Перед публикацией", checkHint: "Сначала проверим требования категории. eBay всё ещё может отклонить настройки аккаунта или объявления.",
    productFix: "Изменить товар", storeFix: "Настроить eBay", store: "Настройки продаж", storeHint: "Доставка, оплата, возврат и место отправки настраиваются один раз для магазина.",
    connect: "Подключите аккаунт продавца eBay.", setupMissing: "Выберите место отправки и правила доставки, оплаты и возврата в настройках eBay.",
    setupReady: "Настройки магазина сохранены и будут использованы для объявления.", unsupportedMarket: "Пока поддерживаются только США и USD.",
    pending: "Публикация выполняется. Дождитесь результата перед повторной отправкой.", checkFailed: "Не удалось проверить требования eBay. Ничего не отправлено. Повторите попытку.",
    sandbox: "Sandbox / тестовое объявление", production: "Настоящее объявление eBay", environmentUnknown: "Перед публикацией подтвердите среду в настройках магазина.",
    sandboxHint: "Будет создано тестовое объявление, а не товар для продажи на основном eBay.", productionHint: "Будет создано или обновлено настоящее объявление на eBay.",
    stock: "Изменение остатков", catalog: "Товары", create: "Добавить товар", draft: "Черновик", open: "Проверить объявление", comingSoon: "Публикация на Shopify и Etsy пока недоступна.",
    optional: "Необязательные данные", count: "Количество", price: "Цена (USD)", loadFailed: "Не удалось загрузить проверки. Обновите страницу перед публикацией."
  },
  uk: {
    basics: "1. Ваш товар", basicsHint: "Додайте фото та інформацію для покупця. Поки один розмір або варіант на товар.",
    ebay: "2. Дані для eBay", ebayHint: "Оберіть категорію за назвою. Ми завантажимо допустимі стани й обов'язкові характеристики.",
    review: "3. Перевірка та публікація", save: "Зберегти й перевірити", saving: "Зберігаємо...", draftHint: "Зберігається чернетка. Товар ще не публікується.",
    advanced: "Додаткові налаштування", skuHint: "Створюється автоматично, якщо залишити порожнім. Не змінюйте після публікації, щоб не створити дублікат.",
    overrides: "Інша назва, опис або ціна на eBay", overridesHint: "Необов'язково. Залиште порожнім, щоб використати дані товару вище.",
    variants: "Товар має варіанти. Вони збережуться, але для публікації на eBay поки потрібен окремий товар з одним варіантом.",
    photosHint: "Перше фото стане обкладинкою. Завантажте чіткі фото самого товару.", mainPhoto: "Зробити обкладинкою", cover: "Обкладинка",
    search: "Знайти категорію", searchHint: "Шукайте англійською, наприклад T-Shirts або Sneakers. Оберіть розділ, що відповідає товару.",
    category: "Категорія", manual: "Я вже знаю ID категорії eBay", noResults: "Категорії не знайдено. Спробуйте коротше слово англійською.",
    change: "Змінити категорію", retry: "Повторити", conditionHint: "Вкажіть справжній стан: новий, вживаний, з бирками чи без. Варіанти залежать від категорії.",
    history: "Попередні спроби", result: "Результат останньої публікації", noJobs: "Товар ще не опубліковано.",
    publish: "Опублікувати на eBay", update: "Опублікувати / оновити на eBay", checking: "Перевіряємо вимоги eBay...", sending: "Надсилаємо...",
    checks: "Перед публікацією", checkHint: "Спочатку перевіримо вимоги категорії. eBay все ще може відхилити налаштування акаунта чи оголошення.",
    productFix: "Змінити товар", storeFix: "Налаштувати eBay", store: "Налаштування продажів", storeHint: "Доставка, оплата, повернення та місце відправлення налаштовуються один раз для магазину.",
    connect: "Підключіть акаунт продавця eBay.", setupMissing: "Оберіть місце відправлення та правила доставки, оплати й повернення в налаштуваннях eBay.",
    setupReady: "Налаштування магазину збережено й буде використано для оголошення.", unsupportedMarket: "Поки підтримуються лише США та USD.",
    pending: "Публікація триває. Дочекайтеся результату перед повторним надсиланням.", checkFailed: "Не вдалося перевірити вимоги eBay. Нічого не надіслано. Спробуйте ще раз.",
    sandbox: "Sandbox / тестове оголошення", production: "Справжнє оголошення eBay", environmentUnknown: "Перед публікацією підтвердьте середовище в налаштуваннях магазину.",
    sandboxHint: "Буде створено тестове оголошення, а не товар для продажу на основному eBay.", productionHint: "Буде створено або оновлено справжнє оголошення на eBay.",
    stock: "Зміна залишків", catalog: "Товари", create: "Додати товар", draft: "Чернетка", open: "Перевірити оголошення", comingSoon: "Публікація на Shopify та Etsy поки недоступна.",
    optional: "Необов'язкові дані", count: "Кількість", price: "Ціна (USD)", loadFailed: "Не вдалося завантажити перевірки. Оновіть сторінку перед публікацією."
  }
};
